[2025-02-07T21:41:12.916+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:41:12.921+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:40:00+00:00 [queued]>
[2025-02-07T21:41:12.924+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:40:00+00:00 [queued]>
[2025-02-07T21:41:12.925+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:41:12.930+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_analysis> on 2025-02-07 12:40:00+00:00
[2025-02-07T21:41:12.937+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29469) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:41:12.938+0900] {standard_task_runner.py:72} INFO - Started process 29473 to run task
[2025-02-07T21:41:12.936+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_analysis', 'scheduled__2025-02-07T12:40:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmp9qx38kyj']
[2025-02-07T21:41:12.938+0900] {standard_task_runner.py:105} INFO - Job 46: Subtask run_analysis
[2025-02-07T21:41:12.959+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:40:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:41:12.990+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:40:00+00:00'
[2025-02-07T21:41:12.991+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:41:13.000+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:41:13.000+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python model/analysis/load_and_analysis3.py']
[2025-02-07T21:41:13.004+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:41:14.536+0900] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-07T21:41:14.536+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/Desktop/bitcoin-data/model/analysis/load_and_analysis3.py", line 106, in <module>
[2025-02-07T21:41:14.536+0900] {subprocess.py:106} INFO -     df_combined = pd.read_csv("/gold/combined_data.csv", index_col='datetime', parse_dates=True)
[2025-02-07T21:41:14.537+0900] {subprocess.py:106} INFO -                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:41:14.537+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[2025-02-07T21:41:14.537+0900] {subprocess.py:106} INFO -     return _read(filepath_or_buffer, kwds)
[2025-02-07T21:41:14.537+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:41:14.537+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[2025-02-07T21:41:14.538+0900] {subprocess.py:106} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-02-07T21:41:14.538+0900] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:41:14.538+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[2025-02-07T21:41:14.538+0900] {subprocess.py:106} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-02-07T21:41:14.538+0900] {subprocess.py:106} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -     self.handles = get_handle(
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -                    ^^^^^^^^^^^
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -     handle = open(
[2025-02-07T21:41:14.539+0900] {subprocess.py:106} INFO -              ^^^^^
[2025-02-07T21:41:14.540+0900] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/gold/combined_data.csv'
[2025-02-07T21:41:14.839+0900] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-07T21:41:14.845+0900] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-07T21:41:14.849+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=run_four_python_files, task_id=run_analysis, run_id=scheduled__2025-02-07T12:40:00+00:00, execution_date=20250207T124000, start_date=20250207T124112, end_date=20250207T124114
[2025-02-07T21:41:14.855+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:41:14.855+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 46 for task run_analysis (Bash command failed. The command returned a non-zero exit code 1.; 29473)
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-07T21:41:14.881+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T21:41:14.888+0900] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:41:14.888+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
