[2025-02-07T21:44:13.471+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:44:13.477+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:43:00+00:00 [queued]>
[2025-02-07T21:44:13.480+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:43:00+00:00 [queued]>
[2025-02-07T21:44:13.480+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:44:13.486+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_gold> on 2025-02-07 12:43:00+00:00
[2025-02-07T21:44:13.494+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29763) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:44:13.494+0900] {standard_task_runner.py:72} INFO - Started process 29771 to run task
[2025-02-07T21:44:13.493+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_gold', 'scheduled__2025-02-07T12:43:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmprsbnc47p']
[2025-02-07T21:44:13.495+0900] {standard_task_runner.py:105} INFO - Job 57: Subtask run_gold
[2025-02-07T21:44:13.518+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:43:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:44:13.553+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:43:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:43:00+00:00'
[2025-02-07T21:44:13.553+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:44:13.563+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:44:13.564+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python gold/combine_data.py']
[2025-02-07T21:44:13.568+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:44:13.981+0900] {subprocess.py:106} INFO - 결합된 데이터가 'combined_data.csv'에 저장되었습니다.
[2025-02-07T21:44:14.016+0900] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-07T21:44:14.026+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:44:14.027+0900] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=run_four_python_files, task_id=run_gold, run_id=scheduled__2025-02-07T12:43:00+00:00, execution_date=20250207T124300, start_date=20250207T124413, end_date=20250207T124414
[2025-02-07T21:44:14.040+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T21:44:14.050+0900] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:44:14.051+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
